### PR TITLE
Fix Data-Set Search

### PR DESCRIPTION
**Pull request by awharn**
**What It Does**

Fixes a logic error that results in search terms toward the beginning of a line not being found
Implements @adam-wolfe's suggested solution and adds regression tests

**How to Test**

**Review Checklist**
I certify that I have:
- [x] tested my changes
- [x] added/updated automated tests
- [x] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

### CODE REVIEW

**Review by traeok — APPROVED** [review]
LGTM, thanks for the fix @awharn 👍

**Review by adam-wolfe — APPROVED** [review]
LGTM, thanks @awharn.

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @awharn for adding a regression test 🙂

**Review by anaxceron — APPROVED** [review]
looks great, thanks @awharn

**Pull request merged**
