### PR TITLE
Shrinkwrap + Node:16.13.1 on Jenkinsfile

### PR DESCRIPTION
**Pull request by zFernand0**

### CODE REVIEW

**Comment by zFernand0** [comment]
To fix the Jenkinsfile issue we may need to update the version controller library:
https://github.com/zowe/zowe-cli-version-controller/blob/master/src/org/zowe/pipelines/nodejs/NodeJSPipeline.groovy#L979

**Review by gejohnston — APPROVED** [review]

**Review by gejohnston — DISMISSED** [review]

**Review by awharn — APPROVED** [review]

**Comment by zFernand0** [comment]
Is the `check-changelog` issue in the `pr-merge` build related to https://github.com/zowe/zowe-cli/issues/1265 ?

**Comment by zFernand0** [comment]
Is the `check-changelog` issue in the `pr-merge` build related to https://github.com/zowe/zowe-cli/issues/1265 ?
Or maybe I should just update all packages' changelog that have imperative as a regular dependency ? 😋

**Comment by zFernand0** [comment]
this was previously approved
apologies for dismissing the reviews with more commits 😢

**Pull request merged**
