### PR TITLE
Fix incorrect syntax of VSAM example

### LINKED ISSUE #823: Create VSAM secondary-space wrong example
@mehmetalpsumer reported the following issue in CLI help examples: 

The example given for creating a linear VSAM with secondary-space being 1MB is wrong, as secondary-space must take a number, not a string. It is on the zowe › zos-files › create › data-set-vsam (see link below) page, 2nd code example in the Examples section.

In the help text: https://docs.zowe.org/stable/web_help/index.html?p=zowe_zos-files_create_data-set-vsam

### PR DESCRIPTION
**Pull request by t1m0thyj**
Fixes #823

### CODE REVIEW

**Review by awharn — APPROVED** [review]
This looks good to me! Is this something that we are going to release immediately as a patch?

**Review by zFernand0 — APPROVED** [review]
LGTM

**Comment by zFernand0** [comment]
> Is this something that we are going to release immediately as a patch?

We can do that or we can wait for any other PR to be merged here or in imperative.

**Comment by awharn** [comment]
> 
> 
> > Is this something that we are going to release immediately as a patch?
> 
> We can do that or we can wait for any other PR to be merged here or in imperative.

I have no preference, I was just curious. 😄

**Comment by t1m0thyj** [comment]
> I have no preference, I was just curious. 😄

I also don't have much preference 🙂

Would it make sense to release this as a patch after https://github.com/zowe/zowe-cli-version-controller/pull/109 and https://github.com/awharn/check_changelog_action/pull/7 are merged? If so I can push a commit to update the Jenkinsfile in this PR. After merging it and bumping the version, the repo will have a new Git tag and we can test that the Lerna changelog check is fixed in #836

**Comment by awharn** [comment]
> 
> 
> > I have no preference, I was just curious. 😄
> 
> I also don't have much preference 🙂
> 
> Would it make sense to release this as a patch after [zowe/zowe-cli-version-controller#109](https://github.com/zowe/zowe-cli-version-controller/pull/109) and [awharn/check_changelog_action#7](https://github.com/awharn/check_changelog_action/pull/7) are merged? If so I can push a commit to update the Jenkinsfile in this PR. After merging it and bumping the version, the repo will have a new Git tag and we can test that the Lerna changelog check is fixed in #836

I think that would make sense. 😄

**Comment by zFernand0** [comment]
> > I have no preference, I was just curious. 😄
> 
> I also don't have much preference 🙂
> 
> Would it make sense to release this as a patch after [zowe/zowe-cli-version-controller#109](https://github.com/zowe/zowe-cli-version-controller/pull/109) and [awharn/check_changelog_action#7](https://github.com/awharn/check_changelog_action/pull/7) are merged? If so I can push a commit to update the Jenkinsfile in this PR. After merging it and bumping the version, the repo will have a new Git tag and we can test that the Lerna changelog check is fixed in #836

both PRs referenced have been merged.
Is this one good to go?

**Comment by t1m0thyj** [comment]
> both PRs referenced have been merged.
> Is this one good to go?

Although this PR is now passing, I suggest we wait until https://github.com/zowe/zowe-cli-version-controller/pull/110 is merged, since there were more issues discovered with our automation for Lerna monorepos which may affect the deploy stage 😢

**Pull request merged**
