### PR TITLE
doc(cert): Document limitation on cert files

### PR DESCRIPTION
**Pull request by zFernand0**
**What It Does**

Add information about the password-protected certificate file limitations on the CLI.

**How to Test**

Just take a look at the web-help and help text
|CLI Help Text|Web Help Text|
|-|-|
|image|image|

**Review Checklist**
I certify that I have:
- [x] tested my changes
- [x] added/updated automated tests
- [x] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

Checkout the zowe/docs-site PR:
- https://github.com/zowe/docs-site/pull/3341

### CODE REVIEW

**Review by t1m0thyj — APPROVED** [review]
The note added LGTM 👍 

Won't the `--cert-file` and `--cert-key-file` options almost always be used together and appear next to each other in doc? Wondering if having the note in both places is duplication and maybe we only need it once on `--cert-file`?

**Comment by t1m0thyj** [comment]
Sorry, could you please fix the lint warnings for max line length? 😿

**Review by gejohnston — APPROVED** [review]

**Review by traeok — APPROVED** [review]
LGTM, thanks @zFernand0!

**Comment by zFernand0** [comment]
The windows failure was just a "post-checkout" error. However, the entire pipeline worked. 😋 
https://github.com/zowe/zowe-cli/actions/runs/7426069642/job/20209022410?pr=2006
image

**Review by t1m0thyj — APPROVED** [review]

**Pull request merged**
