### PR TITLE
upload dir-to-uss with .zosattributes

### PR DESCRIPTION
**Pull request by matthewpwilson**
Add support for a .zosattributes metadata file as described in #207 

We weren't quite sure what to do with the description of the file format.  I've added it to the help for dir-to-uss, but it does make it quite long. Also it's not easy to format the example nicely.  https://github.com/zowe/imperative/pull/203 is needed in order to render the Markdown correctly. We have a few minor updates to words to come too but wanted to get this PR raised for review. 

The default behaviours when using a .zosattributes file turn out to be the opposite of the existing defaults of dir-to-uss i.e. dir-to-uss defaults to uploading in text mode (converting to EBCDIC), whereas with a .zosattributes the default is uploading in binary and tagging as ISO8859-1.   We felt this was a more sane default for application deployment use-cases but it's potentially confusing having different defaults.

### CODE REVIEW

**Comment by ChrisBoehmCA** [comment]
Hi, thanks for the changes

>The default behaviours when using a .zosattributes file turn out to be the opposite of the existing defaults of dir-to-uss i.e. dir-to-uss defaults to uploading in text mode (converting to EBCDIC), whereas with a .zosattributes the default is uploading in binary and tagging as ISO8859-1. We felt this was a more sane default for application deployment use-cases but it's potentially confusing having different defaults.

This would constitute a breaking change then and would mean it couldn't be ported to our lts-incremental branch, which means most people won't be using it for several months (possibly until january 2020, not sure of the timeline of the next major release) unless they choose to install with the `@latest` or `@daily` tags

**Comment by matthewpwilson** [comment]
> This would constitute a breaking change
OK, so seems best to keep the currently behaviour for dir-to-uss without .zosattributes and live with the fact that the default is difference once a .zosattributes exists

**Comment by ChrisBoehmCA** [comment]
So to clarify are you going to change the implementation so that it's no longer a breaking change? Thanks

**Comment by matthewpwilson** [comment]
I don't think it is a breaking change currently - I've not changed the existing behaviour or defaults when using dir-to-uss without a .zosattributes file. It's only when you use a .zosattributes file the default behaviour changes.  Is this acceptable?

**Comment by ChrisBoehmCA** [comment]
Yeah, that makes sense. Thanks. Please resolve the merge conflicts in this PR and then I will try to review soon

**Comment by matthewpwilson** [comment]
Should be ready for review now. I'm seeing one test case in `packages/zosfiles/__tests__/__system__/cli/upload/dtu/cli.dir.upload.dtu.system.test.ts` fail:
```
Upload directory to USS › Success scenarios › should give error when upload local directory to
 USS directory in default ascii if it contains also binary files

    expect(received).toContain(expected) // indexOf

    Expected substring: "Rest API failure with HTTP(S) status 500"
    Received string:    ""Upload directory to USS › Success scenarios › should give error when upload local directory to
 USS directory in default ascii if it contains also binary files

    expect(received).toContain(expected) // indexOf

    Expected substring: "Rest API failure with HTTP(S) status 500"
    Received string:    ""
```
but this fails for me at master as well so I don't believe I've regressed it.

**Comment by ChrisBoehmCA** [comment]
Thanks. I'll open an issue for the failing test

**Comment by matthewpwilson** [comment]
Thanks for sorting out those tests, I am indeed a Linux user so hadn't seen those issues. 
I'll port to lts-incremental in due course.

**Pull request merged**
