### PR TITLE
help with tests

### PR DESCRIPTION
**Pull request by zFernand0**
Signed-off-by: zFernand0 <fernando.rijocedeno@broadcom.com>

### CODE REVIEW

**Comment by awharn** [comment]
It looks good to me. Thanks for getting that test suite working: I was completely stumped trying to figure that out.  😄

**Comment by zFernand0** [comment]
Just opened the PR to maybe spark some discussion around updating the TEST_ENV class.
@awharn, @tjohnsonBCM, @ChrisBoehmCA, @tucker01, @dkelosky, thoughts?

**Comment by awharn** [comment]
I think that a TEST_ENV option to put everything inside of a .zowe directory would be nice to have. It's where we expect to find everything related to the CLI and profiles, at least for the time being. As we move forward with these SDKs, I can see more situations arising where people are looking in that directory or providing functions that look in that directory.

**Comment by ChrisBoehmCA** [comment]
I think it's OK to even automatically append /.zowe (if it's not already there and use that as a`workingDir` in TestEnvironment if it doesn't break anything else.  Just curious why  `.zowe/` needed to be there for this test? Because .zowe is not created if a ZOWE_CLI_HOME environment variable is specified, so if not having .zowe breaks the test, it might break the thing it's testing when a user doesn't manually include .zowe in ZOWE_CLI_HOME

**Comment by zFernand0** [comment]
> I think it's OK to even automatically append /.zowe (if it's not already there and use that as a`workingDir` in TestEnvironment if it doesn't break anything else. Just curious why `.zowe/` needed to be there for this test? Because .zowe is not created if a ZOWE_CLI_HOME environment variable is specified, so if not having .zowe breaks the test, it might break the thing it's testing when a user doesn't manually include .zowe in ZOWE_CLI_HOME

Adding the `/.zowe` automatically will not cause issues for any other tests (I'll confirm that later today), but that only solves half of the problem since the `getZoweDir` function appends `.zowe` to the `os.homedir`.

**Pros & Cons:** Having an option will at least clear the testName a little bit, but if people need to back out (like in this test), it may not be intuitive as to why we are doing `os.homedir() + "/.."`

**Context:** This particular tests has to do with getting default profiles, so we tried to simulate a real scenario as much as possible 😋

**Comment by tjohnsonBCM** [comment]
> Because .zowe is not created if a ZOWE_CLI_HOME environment variable is specified, so if not having .zowe breaks the test, it might break the thing it's testing when a user doesn't manually include .zowe in ZOWE_CLI_HOME

The thing being tested here is the value returned by the getter `ImperativeConfig.instance.cliHome`. If the ZOWE_CLI_HOME env var is specified, it will return that path without appending ".zowe" to the end. If the env var is *not* specified, then ".zowe" will always be appended to the end.

In this test, ZOWE_CLI_HOME was not defined, hence why ".zowe" was required at the end of the path. Perhaps a simpler way to fix this test would have been to define `process.env.ZOWE_CLI_HOME`, but we didn't think of that 🙂

**Comment by ChrisBoehmCA** [comment]
OK thanks I see. Wasn’t sure if setting the environment variable would invalidate the test or not. Just an idea

**Comment by zFernand0** [comment]
🤯 Thanks for the suggestion @ChrisBoehmCA and @tjohnsonBCM 😋 
https://github.com/zowe/zowe-cli/pull/841/commits/ddca0ae549c60182512fb2f6299636f3a144db54

**Pull request merged**
