### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zFernand0**
More info on how to add sonarcloud badges
- https://stackoverflow.com/a/62847411

### CODE REVIEW

**Review by traeok — APPROVED** [review]
wonder why the coverage is different between the two 🤔 

LGTM, thanks @zFernand0

**Review by t1m0thyj — COMMENTED** [review]
Thanks for doing this 👍 

Also curious why the numbers are different - should we investigate before merging or plan to resolve it in the future?

**Comment by zFernand0** [comment]
Sonar cloud coverage is a bit out of date.
Looking into it now
👀 https://github.com/zowe-actions/octorelease-script/blob/master/scripts/sonarConfig.ts#L41

**Comment by t1m0thyj** [comment]
Closed the PR because it seems like Sonar is receiving accurate data but reports coverage differently from other tools.

> SonarCloud.io shows a breakdown of the coverage info:
> image
> 
> The line coverage of 92% and branch coverage of 82% pretty much match what Jest itself reports, so I think the overall coverage number is calculated by Sonar using some formula that is essentially a weighted average of the other coverage numbers.

Thanks @traeok for tracking down their coverage formula here: https://docs.sonarcloud.io/digging-deeper/metric-definitions/

**Pull request closed without merging**
