### PR TITLE
Add workflow to update issue and PR status on GH project board

### PR DESCRIPTION
**Pull request by t1m0thyj**
### Problem
GitHub Projects doesn't let us choose different columns for new issues vs pull requests, so they both end up in "New Issues":
image

### Solution
This PR adds a GitHub workflow that is triggered on PR and issue events, which will update the column/status of that item in the GitHub project.
* When PR is opened or re-opened: "New Issues" -> "In Progress"
* When PR is converted to draft: "Review/QA" -> "In Progress"
* When PR is marked ready for review: "In Progress" -> "Review/QA"
* When issue is labelled with "priority-`X`" or "Epic": "New Issues" -> "`X` Priority" or "Epics"

**Note:** If we want this behavior across all CLI repos, we need to add this workflow to each one.

### CODE REVIEW

**Comment by t1m0thyj** [comment]
Looks like the `zowe-robot` token is missing the permission to manage GitHub projects: https://github.com/zowe/zowe-cli/actions/runs/7389202260/job/20101539667?pr=1997

**Review by zFernand0 — APPROVED** [review]
Seems like this should work 😋

**Comment by zFernand0** [comment]
> Looks like the `zowe-robot` token is missing the permission to manage GitHub projects: https://github.com/zowe/zowe-cli/actions/runs/7389202260/job/20101539667?pr=1997

We might need an org admin to help us out with this one 😋 
CC: @MarkAckert 👀

**Review by gejohnston — APPROVED** [review]

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
Thanks for simplifying the steps! 😋

**Pull request merged**
