### PR TITLE
Update @types/node to current LTS version

### PR DESCRIPTION
**Pull request by t1m0thyj**
Forgot to update the `@types/node` package in #1497. Updated it to 14.x, I believe this is the best version to use currently. If we used a newer version like 16.x, we might accidentally use a Node.js feature missing in 14.x which we still support.

### CODE REVIEW

**Review by zFernand0 — APPROVED** [review]

**Comment by zFernand0** [comment]
do you mind adding the `for-review`, `keep`, and `third-party` labels to the `stale.yml` workflow
https://github.com/zowe/zowe-cli/blob/master/.github/workflows/stale.yml#L23

or at least the `keep` 😋

**Review by gejohnston — APPROVED** [review]

**Comment by t1m0thyj** [comment]
> do you mind adding the `for-review`, `keep`, and `third-party` labels to the `stale.yml` workflow https://github.com/zowe/zowe-cli/blob/master/.github/workflows/stale.yml#L23
> 
> or at least the `keep` 😋

Sure, we can discuss labels to add at our next standup 🙂 Should I also update the `ssh2` dependency?

**Comment by zFernand0** [comment]
> > do you mind adding the `for-review`, `keep`, and `third-party` labels to the `stale.yml` workflow https://github.com/zowe/zowe-cli/blob/master/.github/workflows/stale.yml#L23
> > or at least the `keep` 😋
> 
> Sure, we can discuss labels to add at our next standup 🙂 Should I also update the `ssh2` dependency?

yeah, maybe we can address this issue 😋 
- #1510 
- #1516

**Review by KevinLoesch1 — APPROVED** [review]

**Review by awharn — APPROVED** [review]

**Comment by zFernand0** [comment]
Thanks for updating the ssh2 package 🥳

**Pull request merged**
