### PR TITLE
Update Imperative dependency to 4.7.2

### PR DESCRIPTION
**Pull request by tjohnsonBCM**
This addresses zowe/imperative#416 which was resolved in Imperative in zowe/imperative#415.

### CODE REVIEW

**Comment by awharn** [comment]
Looks good to me. Pretty straightforward.

**Comment by awharn** [comment]
I don't think @tjohnsonBCM or I can merge, @gejohnston.

**Comment by gejohnston** [comment]
@tjohnsonBCM , @awharn  -  Would you like me to merge it now?

**Comment by awharn** [comment]
> @tjohnsonBCM , @awharn - Would you like me to merge it now?

Yes, please. 😄

**Pull request merged**
