### PR TITLE
Delete Archived CLI + List Archived API

### PR DESCRIPTION
**Pull request by melvl01**
Created CLI for Delete Archived command. For this is needed API for List Archived. 
Added unit tests, system tests and integration tests (for CLI only).

CLI help

 COMMAND NAME
 ------------
   archived-workflow | arw

 DESCRIPTION
 -----------
   Delete an archived workflow from z/OSMF

 USAGE
 -----
   zowe zos-workflows delete archived-workflow [options]

 OPTIONS
 -------
   --workflow-key  | --wk (string)

      Delete an archived workflow by specified workflow key

   --workflow-name  | --wn (string)

      Delete an archived workflow by specified workflow name

 EXAMPLES
 --------
   - To delete an archived workflow from z/OSMF with
   workflow key "d043b5f1-adab-48e7-b7c3-d41cd95fa4b0":

      $ zowe zos-workflows delete archived-workflow --workflow-key "d043b5f1-adab-48e7-b7c3-d41cd95fa4b0"

   - To delete an archived workflow from z/OSMF with
   workflow name "testWorkflow":

      $ zowe zos-workflows delete archived-workflow --workflow-name "testWorkflow"

### CODE REVIEW

**Comment by ChrisBoehmCA** [comment]
Please port these changes to master as well. vulnerabilities should be fixed soon to fix your jenkins build

**Comment by melvl01** [comment]
Close to re-run tests

**Comment by ChrisBoehmCA** [comment]
One snapshot needs updated

**Comment by ChrisBoehmCA** [comment]
You might have to do "npm install --save @zowe/imperative@lts-incremental" first in order to get the snapshot to pass

**Comment by melvl01** [comment]
I am working on it, but on my local it is passing even with latest changes... I will try do "npm install --save @zowe/imperative@daily"  thanks

**Comment by ChrisBoehmCA** [comment]
Sorry I made a little mistake there. The command for this branch should be: `npm install --save @brightside/imperative@lts-incremental`

**Comment by melvl01** [comment]
Snapshot updated, I was missing the exitCode: 0...

**Pull request merged**
