### PR TITLE
Add missing yields and other fixes

### PR DESCRIPTION
**Pull request by awharn**
**What It Does**

Fixes SonarCloud bugs

**How to Test**

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [x] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

### CODE REVIEW

**Comment by awharn** [comment]
Unfortunately, there is no good way to tell if this fixes all the bugs on SonarCloud or not. More work may need to be done after this PR is merged.

**Review by gejohnston — APPROVED** [review]
Don't you hate it when you have to fix our test handlers? Thanks for working through all of them.

**Review by traeok — APPROVED** [review]
LGTM, thanks for these fixes @awharn!

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @awharn for fixing these code smells especially the pesky `Imperative.init` one 😋

**Pull request merged**
