### PR TITLE
provided requested fix to zos-jobs list --help-examples (same changes from vnext)

### PR DESCRIPTION
**Pull request by ATorrise**
**What It Does**
same fix to description as in recent vnext pr 

**How to Test**
run `zos-jobs list --help-examples` to see string concatenation issue resolved

**Review Checklist**
I certify that I have:
- [x] tested my changes
- [x] added/updated automated tests
- [x] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
Not sure if we need a changelog/new-version for this help text update.
If we do not plan to release it as a new version, then we should do `release-current` 😋

**Comment by ATorrise** [comment]
> release-current

@t1m0thyj ?

**Comment by ATorrise** [comment]
> LGTM! 😋 Not sure if we need a changelog/new-version for this help text update. If we do not plan to release it as a new version, then we should do `release-current` 😋

@t1m0thyj ?

**Comment by t1m0thyj** [comment]
> > LGTM! 😋 Not sure if we need a changelog/new-version for this help text update. If we do not plan to release it as a new version, then we should do `release-current` 😋
> 
> @t1m0thyj ?

I think release-current is fine, we can probably combine this fix with our next patch/minor release 😋

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @ATorrise!

**Pull request merged**
