### PR TITLE
Copy datasets

### LINKED ISSUE #521: Allow copying of data sets and data set members
Allow data sets and data set members to be copied via the CLI:
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_API_PutDataSetMemberUtilities.htm

### PR DESCRIPTION
**Pull request by CForrest97**
Resolves #521

### CODE REVIEW

**Comment by tucker01** [comment]
This is great. Thanks for contributing. Would you mind adding an integration test that captures the help in a snapshot for your new commands? This helps us review the contribution.

**Comment by CForrest97** [comment]
> This is great. Thanks for contributing. Would you mind adding an integration test that captures the help in a snapshot for your new commands? This helps us review the contribution.
Thanks @tucker01, I have added some integration tests for both the data-set and data-set-member commands

**Comment by tucker01** [comment]
Hi @CForrest97, Thanks for updating the snapshots. I'm going to send this our to our doc, UX, and PO for review doing a formal code review.

Can you shed some light on why you went the route of creating two separate commands? 

This was prototyped some time ago, and I think it was a single command that allowed syntax such as `copy "MY.DATA.SET(MEMBER)" "MY.OTHER.DATA.SET(MEMBER)"`.

With how you have it today, how would one copy a sequential data set to a partitioned data set member?

**Comment by CForrest97** [comment]
> Hi @CForrest97, Thanks for updating the snapshots. I'm going to send this our to our doc, UX, and PO for review before doing a formal code review.
> 
> Can you shed some light on why you went the route of creating two separate commands?
> 
> This was prototyped some time ago, and I think it was a single command that allowed syntax such as `copy "MY.DATA.SET(MEMBER)" "MY.OTHER.DATA.SET(MEMBER)"`.
> 
> With how you have it today, how would one copy a sequential data set to a partitioned data set member?

Hi @tucker01, I wasn't aware that you could copy a sequential data set directly into a partitioned data set. But after trying it out I see you can, so long as you specify the `to-member` name. Therefore it might make sense to have this as one command.
I also didn't know there were any prototypes of copy. Is there somewhere I can view all the prototypes? If so, I could add links on all issues to connect them to their prototypes

**Comment by tucker01** [comment]
I don't think we have the example prototypes anymore. I'll bring this up on our stand-up today and we'll figure out how to proceed.

**Comment by CForrest97** [comment]
After discussions on the stand-up, I will add support for copying a sequential data set into a member by breaking down the issue #521 into multiple component issues in a new branch. Using the code from this branch

**Comment by tucker01** [comment]
> After discussions on the stand-up, I will add support for copying a sequential data set into a member by breaking down the issue #521 into multiple component issues in a new branch. Using the code from this branch

Thanks @CForrest97, would you also mind if you have the time, to update #521 (or a new issue you create for the CLI) with the proposed syntax for the new commands? We can use that as a starting point for discussion with the CLI squad as you're working through the API portion.

**Comment by CForrest97** [comment]
> Thanks @CForrest97, would you also mind if you have the time, to update #521 (or a new issue you create for the CLI) with the proposed syntax for the new commands? We can use that as a starting point for discussion with the CLI squad as you're working through the API portion.

@tucker01, I've created an issue for the CLI functionality with my proposed commands at #580

**Pull request closed without merging**
