### PR TITLE
Update next with changes from master and SCS

### PR DESCRIPTION
**Pull request by t1m0thyj**
Update next branch to include latest changes from master and the SCS plug-in:
* https://github.com/zowe/zowe-cli/pull/1003
* https://github.com/zowe/zowe-cli/pull/1006
* https://github.com/zowe/zowe-cli-scs-plugin/pull/39

### CODE REVIEW

**Review by gejohnston — APPROVED** [review]
Looks good to me.

**Review by awharn — APPROVED** [review]
LGTM! 😄

**Comment by t1m0thyj** [comment]
@gejohnston I've linked your issue (#1010) since I think that this PR fixes it. Could you please confirm?

**Review by zFernand0 — APPROVED** [review]

**Comment by gejohnston** [comment]
I confirmed that this branch successfully builds from a clean environment as referenced in issue #1010. In fact, this was the easiest build I have had of zowe-cli in months.

**Pull request merged**
