### PR TITLE
Fix Upload.unit on Windows (lts-incremental)

### PR DESCRIPTION
**Pull request by matthewpwilson**
Fix problem with path separators for zosattributes tests on Windows as reported in #417 

Same changes as #428

### CODE REVIEW

**Comment by ChrisBoehmCA** [comment]
Hi, 

Thanks for the changes. I'm still getting 4 failures though:

```
  ● z/OS Files - Upload › dirToUSSDir › scenarios with .zosattributes file › should upload files unless they are ignored by attributes

    expect(jest.fn()).toHaveBeenCalledWith(expected)

    Expected mock function to have been called with:
      "test/path/uploadme"
    as argument 1, but it was called with
      "test\\path\\ignoreme".

      "test/path/uploadme"
    as argument 1, but it was called with
      "test\\path\\uploadme".

      1093 |                 expect(USSresponse.success).toBeTruthy();
      1094 |                 expect(attributesMock.fileShouldBeUploaded).toHaveBeenCalledTimes(2);
    > 1095 |                 expect(attributesMock.fileShouldBeUploaded).toHaveBeenCalledWith("test/path/uploadme");
           |                                                             ^
      1096 |                 expect(attributesMock.fileShouldBeUploaded).toHaveBeenCalledWith("test/path/ignoreme");
      1097 | 
      1098 |                 expect(fileToUSSFileSpy).toHaveBeenCalledTimes(1);

      at Object.<anonymous> (packages/zosfiles/__tests__/api/methods/upload/Upload.unit.test.ts:1095:61)
      at fulfilled (packages/zosfiles/__tests__/api/methods/upload/Upload.unit.test.ts:4:58)

  ● z/OS Files - Upload › dirToUSSDir › scenarios with .zosattributes file › should not upload ignored directories

    expect(jest.fn()).toHaveBeenCalledWith(expected)

    Expected mock function to have been called with:
      "test/path/uploaddir"
    as argument 1, but it was called with
      "test\\path\\uploaddir\\uploadedfile".

      "test/path/uploaddir"
    as argument 1, but it was called with
      "test\\path\\ignoredir".

      "test/path/uploaddir"
    as argument 1, but it was called with
      "test\\path\\uploaddir".

      1142 |                 expect(USSresponse).toBeDefined();
      1143 |                 expect(USSresponse.success).toBeTruthy();
    > 1144 |                 expect(attributesMock.fileShouldBeUploaded).toHaveBeenCalledWith("test/path/uploaddir");
           |                                                             ^
      1145 |                 expect(fileToUSSFileSpy).toHaveBeenCalledTimes(1);
      1146 |                 expect(fileToUSSFileSpy).toHaveBeenCalledWith(dummySession,
      1147 |                                                               path.normalize(path.join(testPath, "uploaddir", "uploadedfile")),

      at Object.<anonymous> (packages/zosfiles/__tests__/api/methods/upload/Upload.unit.test.ts:1144:61)
      at fulfilled (packages/zosfiles/__tests__/api/methods/upload/Upload.unit.test.ts:4:58)

  ● z/OS Files - Upload › dirToUSSDir › scenarios with .zosattributes file › should call API to tag files accord to remote encoding

    expect(jest.fn()).toHaveBeenCalledWith(expected)

    Expected mock function to have been called with:
      "UNIT.TEST\\textfile"
    as argument 2, but it was called with
      "UNIT.TEST/binaryfile".
      "text"
    as argument 3, but it was called with
      "binary".
      "ISO8859-1"
    as argument 4, but it was called with
      undefined.

    Difference:

      Comparing two different types of values. Expected string but received undefined.

      "UNIT.TEST\\textfile"
    as argument 2, but it was called with
      "UNIT.TEST/textfile".

      1176 |                 expect(USSresponse.success).toBeTruthy();
      1177 |                 expect(chtagSpy).toHaveBeenCalledTimes(2);
    > 1178 |                 expect(chtagSpy).toHaveBeenCalledWith(dummySession, `${path.normalize(`${dsName}/textfile`)}`, Tag.TEXT, "ISO8859-1");
           |                                  ^
      1179 |                 expect(chtagSpy).toHaveBeenCalledWith(dummySession, `${path.normalize(`${dsName}/binaryfile`)}`, Tag.BINARY);
      1180 |             });
      1181 | 

      at Object.<anonymous> (packages/zosfiles/__tests__/api/methods/upload/Upload.unit.test.ts:1178:34)
      at fulfilled (packages/zosfiles/__tests__/api/methods/upload/Upload.unit.test.ts:4:58)

  ● z/OS Files - Upload › dirToUSSDir › scenarios with .zosattributes file › should call API to tag a file as text that was uploaded in binary mode

    expect(jest.fn()).toHaveBeenCalledWith(expected)

    Expected mock function to have been called with:
      "UNIT.TEST\\asciifile"
    as argument 2, but it was called with
      "UNIT.TEST/asciifile".

      1188 |                 expect(USSresponse.success).toBeTruthy();
      1189 |                 expect(chtagSpy).toHaveBeenCalledTimes(1);
    > 1190 |                 expect(chtagSpy).toHaveBeenCalledWith(dummySession, `${path.normalize(`${dsName}/asciifile`)}`, Tag.TEXT, "ISO8859-1");
           |                                  ^
      1191 |             });
      1192 |         });
      1193 |     });

      at Object.<anonymous> (packages/zosfiles/__tests__/api/methods/upload/Upload.unit.test.ts:1190:34)
      at fulfilled (packages/zosfiles/__tests__/api/methods/upload/Upload.unit.test.ts:4:58)


```

**Comment by ChrisBoehmCA** [comment]
Great, your last push fixed all of the tests. However please fix your signoff on your last commit and then port the changes over to your other PR. Thank you very much

**Comment by zFernand0** [comment]
@matthewpwilson, Could you please update the branch with the lts-incremental?

**Comment by matthewpwilson** [comment]
Hi @zFernand0 as far as I can tell my branch is up-to-date with lts-incremental - the latest commit is b29356d3fb55558512f8b3939412007ce36c79cd

**Comment by zFernand0** [comment]
@matthewpwilson,
I'm terribly sorry. Don't know why I thought it was not up-to-date with the target branch. I thought I already applied the vulnerability fix in this repo. I will be more careful in the future.
There is no need for you to take any actions. We should be able to get this merged in in the next few hours.
Thank you for being patient.

**Pull request merged**
