### PR TITLE
Lts dsntype

### PR DESCRIPTION
**Pull request by Colin-Stone**

### CODE REVIEW

**Comment by tucker01** [comment]
Thanks Colin!

Where did the list of available types come from? I don't see `dsntype` listed as an option in the z/OSMF REST API guides, but I verified that I can create a PDS with type LIBRARY using the CLI.

**Comment by zFernand0** [comment]
will this help?
https://github.com/zowe/zowe-cli/issues/53#issuecomment-511884592

**Comment by zFernand0** [comment]
Thanks for porting BTW :)

**Comment by tucker01** [comment]
Must have been added after 2.1.0: https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.izua700/IZUHPINFO_API_CreateDataSet.htm#CreateDataSet

**Comment by tucker01** [comment]
Actually it looks like its new in z/OS 2.3. 

It's not a problem, I just wanted to double check the values.

**Pull request merged**
