### PR TITLE
Update for issue #440

### PR DESCRIPTION
**Pull request by cycaoecw**
Fix for #440 on MASTER branch.

### CODE REVIEW

**Comment by zFernand0** [comment]
Apologies for the build failures. It seems we are having difficulties with the automation server.

**Comment by cycaoecw** [comment]
@zFernand0 no problem and thanks for your inform. Just want to ask, i want to check details, but it require logon jenkins. After logon, it said access denied.

**Comment by zFernand0** [comment]
> @zFernand0 no problem and thanks for your inform. Just want to ask, i want to check details, but it require logon jenkins. After logon, it said access denied.

So, I assume you already created an account.
- If yes, Have you had read-access in the past?
  - If yes, we need to investigate why your permission was revoked. `please provide your user ID`
  - If no, `please provide your user ID` so we can get you read access.
- If no, Please create one and `please provide your user ID`.

😄 TL;DR: Could you give me your user ID? :-)

**Comment by cycaoecw** [comment]
@zFernand0 yes, I have account already. Would you grant read access to my id `cycao`?

**Comment by zFernand0** [comment]
> @zFernand0 yes, I have account already. Would you grant read access to my id `cycao`?

I don't have permission to do so, but maybe @MarkAckert can help us with this.

**Comment by zFernand0** [comment]
> @zFernand0 yes, I have account already. Would you grant read access to my id `cycao`?

I don't have permission to do so, but maybe @MarkAckert can help us with this.

**Comment by zFernand0** [comment]
Thanks Mark.
@cycaoecw, please check to see if you have read-access already.

**Pull request merged**
