### PR TITLE
Fix isse #325: `zowe files upload ftds` fails on `GET`

### PR DESCRIPTION
**Pull request by uzust01**
This seems to work for me, I made some manual tests (on top of the existing automated). 
Open for feedback :D 

https://github.com/zowe/zowe-cli/issues/325

### CODE REVIEW

**Comment by tucker01** [comment]
While I agree with some of the comments in the issue (about refactoring), this does seem to work as a simple fix. 

However, my concern is that this change relies on the collating sequence that IBM has defined for the return list (e.g. DATA.SET will be index 0 if DATA.SET.OTHER exists). Although, I suppose it wouldn't make much sense if you requested to list DATA.SET with max items 1 and z/OSMF returned DATA.SET.OTHER. It also depends on IBM not attempting to gather attributes on items that were filtered out by setting `X-IBM-Max-Items: 1`.

IBM does provide a `start` query param on ds list, that looks like it could be used to ensure you're getting exactly the data-set you want if you used `dsname=DATA.SET&start=DATA.SET` with the `X-IBM-Max-Items: 1`.

What do you think?

**Comment by uzust01** [comment]
> While I agree with some of the comments in the issue (about refactoring), this does seem to work as a simple fix.
> 
> However, my concern is that this change relies on the collating sequence that IBM has defined for the return list (e.g. DATA.SET will be index 0 if DATA.SET.OTHER exists). Although, I suppose it wouldn't make much sense if you requested to list DATA.SET with max items 1 and z/OSMF returned DATA.SET.OTHER. It also depends on IBM not attempting to gather attributes on items that were filtered out by setting `X-IBM-Max-Items: 1`.
> 
> IBM does provide a `start` query param on ds list, that looks like it could be used to ensure you're getting exactly the data-set you want if you used `dsname=DATA.SET&start=DATA.SET` with the `X-IBM-Max-Items: 1`.
> 
> What do you t

**Comment by uzust01** [comment]
> While I agree with some of the comments in the issue (about refactoring), this does seem to work as a simple fix.
> 
> However, my concern is that this change relies on the collating sequence that IBM has defined for the return list (e.g. DATA.SET will be index 0 if DATA.SET.OTHER exists). Although, I suppose it wouldn't make much sense if you requested to list DATA.SET with max items 1 and z/OSMF returned DATA.SET.OTHER. It also depends on IBM not attempting to gather attributes on items that were filtered out by setting `X-IBM-Max-Items: 1`.
> 
> IBM does provide a `start` query param on ds list, that looks like it could be used to ensure you're getting exactly the data-set you want if you used `dsname=DATA.SET&start=DATA.SET` with the `X-IBM-Max-Items: 1`.
> 
> What do you think?

Idk what I did there with the close and reopen :D 

I was thinking about this, too, and I dropped it.  In `dsname=DATA.SET&start=DATA.SET` DATA.SET will always be the same and regardless of start= being there or not the list will always start at DATA.SET.

**Comment by uzust01** [comment]
Added <start> to the interface for the options parameter of List.dataSet API (and condition to handle it)
This option is not yet exposed to any CLI. It is there to make sure that the now limited to 1 data set list (used in used in Upload.pathToDataSet) starts with the correct data set. 

These changes do not fix the bug described in #325 completely. If the initial data set does not exist and the subsequent data set is archived the same error will occur. 

Currently (to my knowledge) there is no way to determine if a data set is archived without using any "X-IBM-Attributes" and using them will generate a TSO recall prompt asking if you want to restore the data-set.

**Comment by tucker01** [comment]
Thanks @uzust01!

Eventually, we can refactor the `pathToDataSet` API into multiple explicit APIs to avoid the `GET` request. However, these changes should avoid the error as initially reported. If we decide to change the API and interfaces that would be a major breaking change given that they are exported/public, so I'm in favor of this simpler fix for now. 

Plus, these changes add some additional functionality to our existing list APIs, which is great. I have helpers in various projects that determine if a data set exists, and using the max items 1 with the start query param (without requesting attributes) will help me there. 

I'll open a separate issue to track the remaining problem and suggest a rework of the existing APIs when we have more time to devote to it.

**Comment by tucker01** [comment]
Also, if you get a chance, please port to master.

**Comment by zFernand0** [comment]
I like how this was resolved.
Very clever way to fix it! 😄

**Pull request merged**
