### PR TITLE
Perform the actions required to remove perf-timing on v2

### PR DESCRIPTION
**Pull request by awharn**
**What It Does**
Removes Perf-Timing from Zowe CLI and Imperative on v2

**How to Test**
Run normal test suites

**Review Checklist**
I certify that I have:
- [x] tested my changes
- [ ] added/updated automated tests
- [x] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

### CODE REVIEW

**Comment by awharn** [comment]
The coverage drop is due to the coverage tools evaluating that I moved `Imperative.parse` which was not covered. No lines were added.

**Comment by awharn** [comment]
Also, the other behavior observed is that when running tests, Jest may occasionally report double the amount of tests while tests are running. However, the final value reported once tests are complete is correct.

**Review by KevinLoesch1 — APPROVED** [review]
👍

**Review by traeok — APPROVED** [review]
Thanks @awharn 🙂

**Review by zFernand0 — COMMENTED** [review]
I've been too close to the changes in this PR, and I might be biased, but...
LGTM! 😋

**Pull request merged**
