### PR TITLE
#440 Examples for zowe files list uss-files are slightly incorrect

### LINKED ISSUE #440: Examples for zowe files list uss-files are slightly incorrect
These  two examples should have the quote end after "ibmuser" instead of including `--rff` or `--rfh` in the quotes 

```
   - Show the files and directories in path '/u/ibmuser
   displaying only the file or directory name:

      $ zowe zos-files list uss-files "/u/ibmuser --rff name"

   - Show the files and directories in path '/u/ibmuser'
   displaying the headers associated with the file detail:

      $ zowe zos-files list uss-files "/u/ibmuser --rfh"
```

### PR DESCRIPTION
**Pull request by cycaoecw**
Fix #440  Examples for zowe files list uss-files are slightly incorrect

### CODE REVIEW

**Comment by zFernand0** [comment]
Hello @cycaoecw,
Thanks for fixing these items.
Could you please `signoff` your commit?

**Comment by zFernand0** [comment]
Also, there are a few test snapshots that need updated based on this new changes.
The quickest way to do so is by issuing the command: `npm run test:unit -- -u`

**Comment by cycaoecw** [comment]
Hi, @zFernand0 may I how to signoff?

**Comment by zFernand0** [comment]
> Hi, @zFernand0 may I how to signoff?

@cycaoecw 
If you click the [`Details`](https://github.com/zowe/zowe-cli/pull/450/checks?check_run_id=145606305) link next to the DCO check, you should be able to see the recommended steps :) 

- `git commit --amend --signoff`
- `git push --force-with-lease origin lts-incremental`

If you have any further questions, please let us know :)

**Comment by cycaoecw** [comment]
@zFernand0 Thanks for your teaching, sorry i less knowledge on github. I just try to signoff, is that looks good?

**Comment by zFernand0** [comment]
> @zFernand0 Thanks for your teaching, sorry i less knowledge on github. I just try to signoff, is that looks good?

@cycaoecw, looks great. :) Thank you.
Now we are just missing the test snapshots, since there was a change in the user-facing help :)
So after `npm install` and `npm run build`, you shuold be able to run `npm run test:unit -- -u`

**Comment by cycaoecw** [comment]
> > @zFernand0 Thanks for your teaching, sorry i less knowledge on github. I just try to signoff, is that looks good?
> 
> @cycaoecw, looks great. :) Thank you.
> Now we are just missing the test snapshots, since there was a change in the user-facing help :)
> So after `npm install` and `npm run build`, you shuold be able to run `npm run test:unit -- -u`

@zFernand0 yes, i know, but i encountering issue when performing `npm install` and you just reply me in slack that no luck on any try. :(

**Comment by zFernand0** [comment]
@cycaoecw, you are right. Sorry about this.
I'll get back to you as soon as possible.

**Comment by zFernand0** [comment]
@cycaoecw,
Please let me know if you are able to perfom an `npm install` after removing the pacakge-lock and npmrc for now.

**Comment by cycaoecw** [comment]
Hi @zFernand0 , I have run `npm run test:unit -- -u` and all passed. May I know is that ok or I need to commit and push the snap file like `packages/zosfiles/__tests__/cli/list/uss/__snapshots__/Uss.definition.unit.test.ts.snap`?

**Comment by zFernand0** [comment]
> Hi @zFernand0 , I have run `npm run test:unit -- -u` and all passed. May I know is that ok or I need to commit and push the snap file like `packages/zosfiles/__tests__/cli/list/uss/__snapshots__/Uss.definition.unit.test.ts.snap`?

@cycaoecw 
That's perfect!
Could you do the same with the integration tests as well?
`npm run test:integration -- -u`

**Comment by zFernand0** [comment]
Hi again @cycaoecw,
I forgot to ask. Could you please implement the same fix for the `master` branch?

**Comment by cycaoecw** [comment]
hi @zFernand0 , yes, I noticed it. But I am not sure what is the best practice on it? Should I checkout to MASTER branch then update the file again or I just need to merge my change to MASTER branch?

**Comment by zFernand0** [comment]
I'd suggest something similar to what you did with lts-incremental.
- checkout master
- create a branch from there
- Make the changes
- Create a PR that goes into master

**Comment by cycaoecw** [comment]
@zFernand0 thanks for your instructions~ sorry that I less knowledge on it. But may I know is any reason to do it again in MASTER branch instead of merge it?

**Comment by zFernand0** [comment]
@cycaoecw, no worries at all :smile:
Yeah, given that those branches run separate major version (`2.x` for lts-incremental and `5+` for master) we need to avoid introducing any undesired changes on a branch that gets created from another streamline.

**Comment by cycaoecw** [comment]
@zFernand0 understood. I just created PR #453 .

**Comment by zFernand0** [comment]
Thank you @cycaoecw!

**Pull request merged**
