### PR TITLE
Updated example on zowe profiles create zosmf-profile command

### PR DESCRIPTION
**Pull request by ATorrise**
Signed-off-by: Amber Torrise <amber.torrise@broadcom.com>

### CODE REVIEW

**Comment by MikeBauerCA** [comment]
Thanks @ATorrise - this looks good. It was a good call to use the default API Mediation Layer port of 7554 in the example. I think you may need to update the [CLI CHANGELOG](https://github.com/zowe/zowe-cli/blob/master/packages/cli/CHANGELOG.md) as well.

**Review by t1m0thyj — APPROVED** [review]
Thanks for updating this example 🙂 I verified the output by running `zowe profiles create zosmf -h` and noticed that it looks kind of weird to have a period before the semicolon at the end:
image

Typically I would suggest to reword the example description to be a single sentence so we can remove the period, but in this case that seems impossible without creating a huge run-on sentence 🤔 I've added some more reviewers to the PR to get more opinions on this.

**Comment by ATorrise** [comment]
> Typically I would suggest to reword the example description to be a single sentence so we can remove the period, but in this case that seems impossible without creating a huge run-on sentence 🤔 I've added some more reviewers to the PR to get more opinions on this.

Would it make more sense to remove the colon instead?

**Comment by t1m0thyj** [comment]
> > Typically I would suggest to reword the example description to be a single sentence so we can remove the period, but in this case that seems impossible without creating a huge run-on sentence 🤔 I've added some more reviewers to the PR to get more opinions on this.
> 
> Would it make more sense to remove the colon instead?

Good idea, I believe the colon is hardcoded at the end of all command examples by Imperative, so unfortunately we can't easily remove it. I suppose we could enhance Imperative so that if the string ends with a period, then it doesn't add a colon at the end. But that's definitely out of scope so I don't want to suggest more work 🙂

**Review by gejohnston — APPROVED** [review]
Since the team agreed to remove the period after "profile.:" I think we could merge this after that minor update.

**Review by gejohnston — APPROVED** [review]

**Pull request merged**
