### PR TITLE
zos-workflows list api enhancement

### PR DESCRIPTION
**Pull request by uzuko01**
Add a method in List Workflows API to retrieve wf key by given name.

### CODE REVIEW

**Comment by ChrisBoehmCA** [comment]
Would system tests be beneficial for this function?

**Comment by uzuko01** [comment]
@ChrisBoehmCA  I do not think so, the method I added does nothing with the system, just uses an already existing one.

**Comment by ChrisBoehmCA** [comment]
Maybe I'm misunderstanding, but doesn't the call to ` await this.listWorkflows(session, zOSMFVersion, workflowName);` contact z/OSMF?  If so, it seems like there should be a system test for this function

**Comment by uzuko01** [comment]
@ChrisBoehmCA, but there are already system tests for this.listWorkflows()

**Comment by ChrisBoehmCA** [comment]
OK.

**Pull request merged**
