### PR TITLE
Adding eslint to dev dependencies

### PR DESCRIPTION
**Pull request by zFernand0**
`typescript-eslint-parser` was causing an error in the build step.

Installing `eslint` solved the following warning:

`npm WARN typescript-eslint-parser@21.0.2 requires a peer of eslint@>=4.19.1 but none is installed. You must install peer dependencies yourself.`

This fixed the build issue.

### CODE REVIEW

**Comment by ChrisBoehmCA** [comment]
Thanks for fixing. Could you just update the one snapshot test that's failing after merging https://github.com/zowe/imperative/pull/135?

**Comment by zFernand0** [comment]
I agree with Chris W comments that we should look at who is responsible for adding this.
Who wants to do that?

**Comment by MarkAckert** [comment]
Looks like this is a downstream dependency of 'madge', which detects circular dependencies.

**Comment by AHumanFromCA** [comment]
Good work on this :1st_place_medal:

**Pull request merged**
