### PR TITLE
Octorelease changelog updates

### PR DESCRIPTION
**Pull request by ATorrise**
**What It Does**
Addressing [warnings](https://github.com/zowe/zowe-cli/actions/runs/6785415198/job/18446658680) in zowe-actions/octorelease@v1. All changelogs had the following comments added:
```
## Recent Changes

- Breaking: First major version bump for V3
```
**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [x] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Review by awharn — CHANGES_REQUESTED** [review]
Just two small things, then I think this PR should be good to go. :)

**Review by gejohnston — APPROVED** [review]
Approve (after Andrew's comments are addressed)

**Review by traeok — COMMENTED** [review]
Everything looks good, will approve once @awharn's requests are addressed 🙂 Thanks @ATorrise!

**Comment by ATorrise** [comment]
@awharn @gejohnston @traeok sorry guys I didn't see your comments

**Review by traeok — APPROVED** [review]

**Review by zFernand0 — APPROVED** [review]
LGTM! :yum:

**Review by awharn — APPROVED** [review]

**Pull request merged**
