### PR TITLE
Fix/204

### PR DESCRIPTION
**Pull request by Alexandru-Dumitru**
- Fix for https://github.com/zowe/zowe-cli/issues/204 by introducing `--max-concurrent-requests` option on the `files upload dtu` command. 

Refactored `dirToUSSDir` API and CLI to:
- accept pool of options
- create empty directories but skip processing them if empty
- added progress bar  
- added option  `--max-concurrent-requests`

Updated snapshots
Updated command used in test shell script (it was wrongly using file-to-uss)
Updated related tests

### CODE REVIEW

**Comment by zFernand0** [comment]
Thanks for updating the CLIReadme.md file

**Comment by Alexandru-Dumitru** [comment]
Thanks for the review @ChrisBoehmCA @IgorCATech . I will take care of it.

**Comment by Alexandru-Dumitru** [comment]
Hi @ChrisBoehmCA. I've made the changes. Unfortunately, I was not able to replicate all of your errors. For example, I didn't received the UnhandledPromiseRejectionWarning outside of try/catch block from [ERR_UNESCAPED_CHARACTERS]. Also I didn't had the success + error message in the same time.
At least now, with your solution, [ERR_UNESCAPED_CHARACTERS] are handled. 
Could you please check again?
Thanks.


For example:

```
λ ls -R "test dir\
'test dir\':
'dir 2'/

'test dir/dir 2':

λ bright files ul dtu "test dir" "/a/xxx/test dir" --recursive
Unexpected Command Error:
Please review the message and stack below.
Contact the creator of handler:
"C:\Users\xxx\AppData\Roaming\npm\node_modules\@brightside\core\lib\zosfiles\src\cli\upload\dtu\DirToUSSDir.handler"
Message:
Request path contains unescaped characters
Stack:
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:115:13)
    at Object.request (https.js:281:10)
    at Promise (C:\Users\xxx\AppData\Roaming\npm\node_modules\@brightside\core\node_modules\@brightside\imperative\lib\rest\src\client\AbstractRestClient.js:76:39)
    at new Promise (<anonymous>)
    at ZosmfRestClient.performRest (C:\Users\xxx\AppData\Roaming\npm\node_modules\@brightside\core\node_modules\@brightside\imperative\lib\rest\src\client\AbstractRestClient.js:59:16)
    at Function.postExpectString (C:\Users\xxx\AppData\Roaming\npm\node_modules\@brightside\core\node_modules\@brightside\imperative\lib\rest\src\client\RestClient.js:223:34)
    at Function.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\@brightside\core\lib\zosfiles\src\api\methods\create\Create.js:331:43)
    at Generator.next (<anonymous>)
    at C:\Users\xxx\AppData\Roaming\npm\node_modules\@brightside\core\lib\zosfiles\src\api\methods\create\Create.js:17:71
    at new Promise (<anonymous>)
```

After update, I have:

```
λ zowe files ul dtu "test dir" "/a/xxx/test dir" --recursive
success: true
from:    C:\Users\xxx\Documents\WORKSPACE\test dir
to:      /a/xxx/test dir


Directory uploaded successfully.
```

**Comment by Alexandru-Dumitru** [comment]
closing for now. Will split in smaller PRs

**Comment by ChrisBoehmCA** [comment]
OK. I will take another look soon. Thanks for updating

**Comment by Alexandru-Dumitru** [comment]
> Worked great for me. The only weird thing now is that the progress bar keeps going up and down as it uploads each directory -- it must be using the number of files in the current directory to determine the percent complete... but that's acceptable to me, very minor cosmetic issue.
> 
> These changes look good for master. Please open up a pull request with the same changes for lts-incremental (start from a branch based on lts-incremental and use the diff here or cherry picking commits to replicate the change)

Thanks for the feedback. 

Yes, you are right. It is based on each folder, and not on the entire set of file (just because the pool is built on each folder, recursively). 

I will try to merge it with  lts-incremental as well.

Thanks again.

**Pull request merged**
