### PR TITLE
 Delete Archived CLI + List Archived API, porting to Master

### PR DESCRIPTION
**Pull request by melvl01**
Created CLI for Delete Archived command. For this is needed API for List Archived.
Added unit tests, system tests and integration tests (for CLI only).

CLI help

COMMAND NAME
archived-workflow | arw

DESCRIPTION
Delete an archived workflow from z/OSMF

USAGE
zowe zos-workflows delete archived-workflow [options]

OPTIONS
--workflow-key | --wk (string)

  Delete an archived workflow by specified workflow key
--workflow-name | --wn (string)

  Delete an archived workflow by specified workflow name
EXAMPLES
To delete an archived workflow from z/OSMF with
workflow key "d043b5f1-adab-48e7-b7c3-d41cd95fa4b0":

$ zowe zos-workflows delete archived-workflow --workflow-key "d043b5f1-adab-48e7-b7c3-d41cd95fa4b0"

To delete an archived workflow from z/OSMF with
workflow name "testWorkflow":

$ zowe zos-workflows delete archived-workflow --workflow-name "testWorkflow"

### CODE REVIEW

**Comment by ChrisBoehmCA** [comment]
I believe I fixed most of your Jenkins errors in #305. Please pull master in. You may need to make some small changes to snapshots and tests to new commands you've introduced

**Comment by melvl01** [comment]
> I believe I fixed most of your Jenkins errors in #305. Please pull master in. You may need to make some small changes to snapshots and tests to new commands you've introduced

My tests with latest code are passing at the local

**Comment by ChrisBoehmCA** [comment]
One snapshot needs to be updated

**Comment by ChrisBoehmCA** [comment]
You might have to do "npm install --save @zowe/imperative@daily" first in order to get the snapshot to pass

**Comment by melvl01** [comment]
Fixed, I was missing the exitCode: 0, in the snapshot... 
Command "npm install --save @zowe/imperative@daily" helped me to find it.

**Pull request merged**
