### PR TITLE
Files comparison uss files

### PR DESCRIPTION
**Pull request by sarthakjdev**
This PR resolves [Issue#1445](https://github.com/zowe/zowe-cli/issues/1445).

Added a command ```zos-files compare uss-files``` to compare the differences between two uss-files .

Sample command: ```zowe files cmp uss '/u/mentee5/test/test.jcl' '/u/mentee5/test/test.js' ``` 

**It will take two arguments first will be the path to the first uss-file and the second one is the path to the second uss-file.**

**--bv** options can be used to get the same differences in the browser.

### CODE REVIEW

**Comment by zFernand0** [comment]
As expected, code-duplication is only getting worse.
Maybe now is a good time to consider creating that common handler ?

**Review by zFernand0 — APPROVED** [review]
I'm a bit curious why it shows the "Launching browser..." message on a headless environment.
Maybe we should check for that and throw an error ?
Otherwise...
LGTM! 😋

**Review by gejohnston — APPROVED** [review]
Since you are using the zos-files-for-zowe-sdk/Get.USSFile function, it appears that the compare commands should adhere to the encoding of mainframe files, which has been a consistency concern with our upload and download commands. 

Have you confirmed that encoding is honored with the compare command?

**Comment by KevinLoesch1** [comment]
One small fix. In en.ts, there appears to be an extra space before 'uss file' in both positonal parm descriptions. 

```
                    USSFILEPATH1: "The path of the first  uss file you want to compare.",
                    USSFILEPATH2: "The path of the second  uss file you want to compare."
```

**Comment by zFernand0** [comment]
There is an issue in the `Get` SDK which causes this compare command to ignore encoding.
This also happens for the View command group.
More details:
- https://github.com/zowe/zowe-cli/issues/1495

**Pull request merged**
