### PR TITLE
Display daemon messages on standard error

### PR DESCRIPTION
**Pull request by gejohnston**
**What It Does**

The zowe executable, which controls the daemon, now sends all informational messages, progress messages, and error messages to standard error instead of standard output.

**How to Test**

On Linux, you can run a command that starts the daemon and observe that the "starting" message goes to standard error.

```
$ zowe --version 2>stderr.txt
CLI Version: 8.0.0-next.202405161750
Zowe Release Version: V3

$ type stderr.txt
Starting a background process to increase performance ...
```

On Windows, redirecting stdout or stderr on a Zowe command when the daemon is being started locks stdout and stderr until the daemon process is terminated. The Zowe command hangs until the daemon is terminated. This is existing daemon behavior. Instead, run one Zowe command just to start the daemon. You can then redirect stdout and stderr on subsequent Zowe commands.

```
> zowe --version
Starting a background process to increase performance ...
CLI Version: 8.0.0-next.202405161750
Zowe Release Version: V3

# Now that the daemon is running, you can redirect stdout or stderr on Zowe commands.
# Corrupt your environment to cause a daemon communication error, which will
# display an error message on stderr.
#
# In File Explorer, on the file C:\Users\YourUserName\.zowe\daemon\daemon.lock,
# RightClick - Properties - Security - Edit
# Select your user name. Check the following 'Deny' boxes:
# Read & execute, Read, and Write

> zowe --version
Unable to create zowe daemon lock file = C:\Users\ej608771\.zowe\daemon\daemon.lock.
Reason = Access is denied. (os error 5).

> zowe --version 2> stderr.txt
> type stderr.txt
Unable to create zowe daemon lock file = C:\Users\ej608771\.zowe\daemon\daemon.lock.
Reason = Access is denied. (os error 5).

# Undo your changes if you want to run a daemon command ever again.
```

You can also confirm that the daemon's executable version number continues to be displayed on standard output.

```
> zowe --version-exe
1.2.3

> zowe --version-exe > stdout.txt
> type stdout.txt
1.2.3
```

**Review Checklist**
I certify that I have:
- [x] tested my changes
- [x] added/updated automated tests
- [x] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

Similar system tests fail on the master branch when run as daemon. My conclusion is that the system tests have not been affected by this change.

### CODE REVIEW

**Review by traeok — APPROVED** [review]
LGTM, thanks Gene!

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @gejohnston!

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋

**Review by anaxceron — APPROVED** [review]
Looks good @gejohnston, thank you!

**Pull request merged**
