### PR TITLE
provided requested fix to `zos-jobs list --help-examples`

### PR DESCRIPTION
**Pull request by ATorrise**
**What It Does**

**How to Test**
run `zos-jobs list --help-examples` to see string concatenation issue resolved
**Review Checklist**
I certify that I have:
- [x] tested my changes
- [x] added/updated automated tests
- [x] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**
Picked this up just because of the optics of our overwhelming amount of "issues that need help" listed under the cli (these issues are what we have tagged as good first issues) compared to other zowe repos
image

### CODE REVIEW

**Review by adam-wolfe — APPROVED** [review]
LGTM

**Review by zFernand0 — APPROVED** [review]
Thanks for picking this up. 🥳 
Should this be rebased to `master` (and then ported over to `next`)? (or just ported over to `master`) 🤔 
LGTM! 😋

**Comment by ATorrise** [comment]
> Thanks for picking this up. 🥳 Should this be rebased to `master` (and then ported over to `next`)? (or just ported over to `master`) 🤔 LGTM! 😋

Probably master and then ported? @zFernand0

**Comment by zFernand0** [comment]
Since there was a very recent deployment on `master` I think it's fine to go with `next` and then port to `master` 
We can merge said port tomorrow 😋

**Pull request merged**
